language: java

sudo: false 

jdk:
  - openjdk8
  
script: 
# Für Maven
#  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
#  - mvn cobertura:cobertura

# Für Gradle

  gradle check

after_success:
- bash <(curl -s https://codecov.io/bash)
