language: java

sudo: false 

jdk:
  - oraclejdk8
  
script: 

  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
  - mvn cobertura:cobertura
  
  ./gradlew clean check

after_success:
- bash <(curl -s https://codecov.io/bash)