language: java

sudo: false # faster builds

jdk:
  - oraclejdk8
  
script: 

  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
  - mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)