language: java

sudo: false # faster builds

mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jdk:
  - oraclejdk9
  
script: 

  - mvn clean install
  
  - mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)